name: Deploy to GitHub Pages and Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-static:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "Setting environment variables"
        env:
          PCLOUD_EMAIL: ${{ secrets.PCLOUD_EMAIL }}
          PCLOUD_PASSWORD: ${{ secrets.PCLOUD_PASSWORD }}
          IS_FREEZING: 'True'

      - name: Freeze Flask app
        run: python freeze.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  deploy-backend-to-render:
    runs-on: ubuntu-latest
    needs: build-and-deploy-static
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Render CLI
        run: |
          curl -fsSL https://cli.render.com/install.sh | sudo bash

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render login --api-key $RENDER_API_KEY
          render services create --name my-flask-app --repo https://github.com/${{ github.repository }} --branch main --env production
