name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app
      env:
        FLASK_APP: app.py
        FLASK_ENV: development
      run: |
        nohup flask run --host=0.0.0.0 &
        sleep 10s
        curl -v http://localhost:5000
